#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop.

count=0

# Loop while the count is less than 10
while [ "$count" -lt 10 ]
do
  echo "Best School"
  count=$((count + 1)) 
done
