#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop.

count=0

# Loop until the count reaches 10
until [ "$count" -eq 10 ]
do
  echo "Best School"
  count=$((count + 1))  # Increment the counter
done
